version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
